import { OxidationLevel } from "./oxidationLevel";

export const blockOxidationLevels: Record<string, OxidationLevel> = {
  "minecraft:copper_block": OxidationLevel.None,
  "minecraft:copper_bulb": OxidationLevel.None,
  "minecraft:copper_grate": OxidationLevel.None,
  "minecraft:copper_door": OxidationLevel.None,
  "minecraft:copper_trapdoor": OxidationLevel.None,
  "minecraft:chiseled_copper": OxidationLevel.None,
  "minecraft:cut_copper": OxidationLevel.None,
  "minecraft:cut_copper_slab": OxidationLevel.None,
  "minecraft:cut_copper_stairs": OxidationLevel.None,
  "pillars:cut_copper_pillar": OxidationLevel.None,
  //
  "minecraft:exposed_copper": OxidationLevel.Exposed,
  "minecraft:exposed_copper_bulb": OxidationLevel.Exposed,
  "minecraft:exposed_copper_grate": OxidationLevel.Exposed,
  "minecraft:exposed_copper_door": OxidationLevel.Exposed,
  "minecraft:exposed_copper_trapdoor": OxidationLevel.Exposed,
  "minecraft:exposed_chiseled_copper": OxidationLevel.Exposed,
  "minecraft:exposed_cut_copper": OxidationLevel.Exposed,
  "minecraft:exposed_cut_copper_slab": OxidationLevel.Exposed,
  "minecraft:exposed_cut_copper_stairs": OxidationLevel.Exposed,
  "pillars:exposed_cut_copper_pillar": OxidationLevel.Exposed,
  //
  "minecraft:weathered_copper": OxidationLevel.Weathered,
  "minecraft:weathered_copper_bulb": OxidationLevel.Weathered,
  "minecraft:weathered_copper_grate": OxidationLevel.Weathered,
  "minecraft:weathered_copper_door": OxidationLevel.Weathered,
  "minecraft:weathered_copper_trapdoor": OxidationLevel.Weathered,
  "minecraft:weathered_chiseled_copper": OxidationLevel.Weathered,
  "minecraft:weathered_cut_copper": OxidationLevel.Weathered,
  "minecraft:weathered_cut_copper_slab": OxidationLevel.Weathered,
  "minecraft:weathered_cut_copper_stairs": OxidationLevel.Weathered,
  "pillars:weathered_cut_copper_pillar": OxidationLevel.Weathered,
  //
  "minecraft:oxidized_copper": OxidationLevel.Oxidized,
  "minecraft:oxidized_copper_bulb": OxidationLevel.Oxidized,
  "minecraft:oxidized_copper_grate": OxidationLevel.Oxidized,
  "minecraft:oxidized_copper_door": OxidationLevel.Oxidized,
  "minecraft:oxidized_copper_trapdoor": OxidationLevel.Oxidized,
  "minecraft:oxidized_chiseled_copper": OxidationLevel.Oxidized,
  "minecraft:oxidized_cut_copper": OxidationLevel.Oxidized,
  "minecraft:oxidized_cut_copper_slab": OxidationLevel.Oxidized,
  "minecraft:oxidized_cut_copper_stairs": OxidationLevel.Oxidized,
  "pillars:oxidized_cut_copper_pillar": OxidationLevel.Oxidized,
};
